### PR TITLE
Schedule implemetation

### PR DESCRIPTION
**Pull request by agorilla**

### CODE REVIEW

**Comment by anselmh** [comment]
Event ends at 3am latest. Apart from that it looks fine.

**Comment by asciidisco** [comment]
I´d probably would only communicate the start time of a talk, not the end time.
Apart from that. Fine.

**Comment by agorilla** [comment]
End time is removed. 

This should also solve @anselmh's remark as there are no end times anymore.

In general don't think we need to tell when the after party ends in the schedule. The MC can announce that the bar closes at 3 a.m.

**Comment by asciidisco** [comment]
Cool.
If we could add `font-size: 2em; font-weight: bold;` to the `<time>` element, then we have a much more readable (and slightly fancier) display of the start time.

@anselmh What do you think?

**Comment by agorilla** [comment]
Feel free to add it ;)

**Comment by asciidisco** [comment]
Done.

**Comment by anselmh** [comment]
cheers!

**Comment by agorilla** [comment]
Let's call it a schedule :)

**Pull request merged**
