### PR TITLE
Implementation of a new gallery

### PR DESCRIPTION
**Pull request by drublic**
I don't like the current gallery. What do you think of this?

### CODE REVIEW

**Comment by anselmh** [comment]
Nice, like the fresh style. But when zoomed background should be our dark background color and it would be great if you could navigate to the prev/next image as well.

**Comment by drublic** [comment]
True. The plugin I implemented does not support this atm. I could use a full scale gallery plugin.

**Comment by drublic** [comment]
Ich nutze nun ein anderes plugin. könnter euch mal anschauen, was ihr davon haltet.

**Comment by drublic** [comment]
I now use Photoswipe instead of zoom.js. Please have a look :)

**Comment by anselmh** [comment]
I like it very much. :)

**Comment by drublic** [comment]
Nice. Merged.

**Pull request merged**
