### PR TITLE
feat(friends): Add our friendly friends

### PR DESCRIPTION
**Pull request by asciidisco**
- Add friends section
- Add 5 friends (OTS Conf, Workingdraft, Smashing Mag, Offscreen Magazine, Denkbräu)
- Friends behave like sponsors, except that the cards & logos are smaller and friends do not have a description text, only the name

### CODE REVIEW

**Comment by anselmh** [comment]
Very nais! (Except for viewport widths under 280px).

**Comment by asciidisco** [comment]
Feel free to change it, I just put it together as fast as I could & it only works because of <3 & chewing gum ;)

Are >280px viewports a thing?

**Comment by anselmh** [comment]
> Are >280px viewports a thing?

Yes, but what I meant: Not really, therefore go for it and feel free to merge.

**Comment by asciidisco** [comment]
@drublic @agorilla Any remarks from your side(s)?

**Comment by drublic** [comment]
:+1:  Thank you!

**Pull request merged**
