### PR TITLE
Add new speakers styles.

### PR DESCRIPTION
**Pull request by anselmh**

### CODE REVIEW

**Comment by drublic** [comment]
thanks for the update. can you please check the responsiveness again and maybe add an image which is not that blurry.

**Comment by anselmh** [comment]
I improved responsiveness now and have asked Bastian for high-res images.

**Comment by agorilla** [comment]
Pull request to merge speaker branch into master branch on Tuesday.

Made some minor corrections and removed MC section from speakers.
The MC has now an own branch.

**Comment by anselmh** [comment]
Thanks man, I like it!

**Comment by drublic** [comment]
Cool. Photo attribution is sometimes a but "edgy". Please see screenshot.
screen shot 2015-06-29 at 10 18 28

But no show-stopper :)

**Pull request merged**
