### PR TITLE
Include some effects when scrolling

### PR DESCRIPTION
**Pull request by drublic**

### CODE REVIEW

**Comment by anselmh** [comment]
Initial load causes some flickering. Not sure if that’s an issue for us or not. Besides that, cool and good to merge.

**Comment by drublic** [comment]
Which browser does this? Cannot repro on Chrome and FF.

**Comment by anselmh** [comment]
On Firefox. But I guess it’s more the fact that the effect does promote the not so cool loading behavior of the header background image – which is not progressive. So no issue on the effects itself I assume.

**Comment by drublic** [comment]
Just merged this. We can still fix bugs, if necessary. Thank you.

**Pull request merged**
